name: employee_system2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  sizer: 2.0.15
  google_fonts: 6.1.0
  flutter_snake_navigationbar: 0.6.1
  intl: 0.18.1
  dio: 5.3.3
  package_info_plus: 4.2.0
  geolocator: 10.1.0
  geocoding: 2.1.1
  month_picker_dialog: 2.0.2
  modal_bottom_sheet: 2.1.2
  custom_date_range_picker: 1.0.10
  chips_choice: 3.0.1
  file_picker: 6.1.1
  dotted_border: 2.1.0
  remixicon: 1.0.0
  flutter_rounded_date_picker: 3.0.4
  material_dialogs: 1.1.4
  dropdown_button2: 2.3.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/
  uses-material-design: true

